/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserGUI;

import Objects.User;
import UserGUI.UserFrame.Card;

/**
 *
 * @author ManuelVillotti
 */
public class UserDashboardPanel extends javax.swing.JPanel {

        private UserFrame frame;

        public UserDashboardPanel() {
                initComponents();
        }

        /**
         * The function sets the position of the app control buttons on a JFrame.
         * 
         * @param frame   The "frame" parameter is a reference to a JFrame object. It is
         *                casted to a
         *                UserFrame object in the code.
         * @param xBorder The xBorder parameter is an integer value that represents the
         *                amount by which
         *                the x-coordinate of the appControlButtons should be adjusted.
         */
        public void setAppControlButtons(javax.swing.JFrame frame, int xBorder) {
                this.frame = (UserFrame) frame;
                appControlButtons.setAppControl(frame, appControlButtons.getX() + xBorder, appControlButtons.getY());
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                bookingPanel = new javax.swing.JPanel();
                titleTxt = new javax.swing.JLabel();
                appControlButtons = new DesignObjects.AppControlButtons();
                accountPanelGlowingGradient = new DesignObjects.PanelGlowingGradient();
                jLabel5 = new javax.swing.JLabel();
                bookingsPanelGlowingGradient = new DesignObjects.PanelGlowingGradient();
                jLabel4 = new javax.swing.JLabel();

                setMaximumSize(new java.awt.Dimension(3231311, 123131));

                bookingPanel.setBackground(new java.awt.Color(255, 255, 255));
                bookingPanel.setMaximumSize(new java.awt.Dimension(3231311, 123131));
                bookingPanel.setMinimumSize(new java.awt.Dimension(0, 0));

                titleTxt.setBackground(new java.awt.Color(255, 255, 255));
                titleTxt.setFont(new java.awt.Font("Yu Gothic UI", 1, 25)); // NOI18N
                titleTxt.setForeground(new java.awt.Color(102, 153, 255));
                titleTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                titleTxt.setText("Dashboard");

                accountPanelGlowingGradient.setBackgroundLight(new java.awt.Color(255, 255, 255));
                accountPanelGlowingGradient.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                accountPanelGlowingGradientMouseClicked(evt);
                        }
                });

                jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
                jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel5.setText("Edit your account");
                accountPanelGlowingGradient.add(jLabel5);
                jLabel5.setBounds(50, 40, 300, 50);

                bookingsPanelGlowingGradient.setToolTipText("");
                bookingsPanelGlowingGradient.setBackgroundLight(new java.awt.Color(255, 255, 255));
                bookingsPanelGlowingGradient.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                bookingsPanelGlowingGradientMouseClicked(evt);
                        }
                });

                jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
                jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel4.setText("View your bookings");
                bookingsPanelGlowingGradient.add(jLabel4);
                jLabel4.setBounds(50, 40, 300, 50);

                javax.swing.GroupLayout bookingPanelLayout = new javax.swing.GroupLayout(bookingPanel);
                bookingPanel.setLayout(bookingPanelLayout);
                bookingPanelLayout.setHorizontalGroup(
                                bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(bookingPanelLayout.createSequentialGroup()
                                                                .addGap(26, 26, 26)
                                                                .addGroup(bookingPanelLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(bookingPanelLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                .addComponent(appControlButtons,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                74,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(bookingPanelLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(bookingPanelLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(bookingsPanelGlowingGradient,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                399,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(accountPanelGlowingGradient,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                399,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGroup(bookingPanelLayout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(19, 19, 19)
                                                                                                                                .addComponent(titleTxt)))
                                                                                                .addGap(0, 31, Short.MAX_VALUE)))
                                                                .addContainerGap()));
                bookingPanelLayout.setVerticalGroup(
                                bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(bookingPanelLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(appControlButtons,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(titleTxt)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(bookingsPanelGlowingGradient,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                128,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(accountPanelGlowingGradient,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                128,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(23, 23, 23)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(bookingPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(bookingPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        }// </editor-fold>//GEN-END:initComponents

        private void bookingsPanelGlowingGradientMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_bookingsPanelGlowingGradientMouseClicked
                frame.buttonCardAction(Card.BOOKING);
        }// GEN-LAST:event_bookingsPanelGlowingGradientMouseClicked

        private void accountPanelGlowingGradientMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_accountPanelGlowingGradientMouseClicked
                frame.buttonCardAction(Card.ACCOUNT);
        }// GEN-LAST:event_accountPanelGlowingGradientMouseClicked

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private DesignObjects.PanelGlowingGradient accountPanelGlowingGradient;
        private DesignObjects.AppControlButtons appControlButtons;
        private javax.swing.JPanel bookingPanel;
        private DesignObjects.PanelGlowingGradient bookingsPanelGlowingGradient;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel titleTxt;
        // End of variables declaration//GEN-END:variables
}
